### PR TITLE
ENH: Update http to https links

### PR DESCRIPTION
**Pull request by tbirdso**
Automated reformatting with https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/ApplyScriptToRemotes.sh

### CODE REVIEW

**Comment by floryst** [comment]
LGTM.

Verifying https support for the rewritten links would be ideal, but realistically everyone should be on https. The one link I did test 404-ed (a bibliography link), but that's because of the page and not the https link.

**Review by floryst — APPROVED** [review]

**Comment by tbirdso** [comment]
Thanks @floryst . I agree that ideally we would test each link individually, but as I am applying these updates to all ITK remote modules I don't have the manpower to go through each one. I'm relying primarily on CI to make sure nothing breaks in each build, if you or others find broken links in documentation it would be good to correct those in a subsequent fixup.

**Comment by floryst** [comment]
Sure thing; I would much rather you not validate the links anyhow. :) I did a sanity check to ensure that code-related URLs are okay. The majority are non-code rewrites; those links are more tolerable to breakage.

**Comment by PaulHax** [comment]
LGTM!

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
