### PR TITLE
docs: Add BREAKING_CHANGES.md to track beta breaking changes

### PR DESCRIPTION
**Pull request by thewtex**
This manually maintained files help document breaking changes in the 1.0 beta pre-release phase.

Breaking changes also continue to be noted with `BREAKING CHANGE:` in commit messages according to the conventional-changelog angular specification.

### CODE REVIEW

**Review by floryst — APPROVED** [review]
LGTM. @FezVrasta please add any breaking changes that you've noted. 

Separately, we should be more cognizant about marking breaking changes as such. Browsing the CHANGELOG.md, I don't see any recent breaking changes, which means we didn't record them.

**Comment by thewtex** [comment]
> Separately, we should be more cognizant about marking breaking changes as such. Browsing the CHANGELOG.md, I don't see any recent breaking changes, which means we didn't record them.

Yes, we should be as cognizant as possible about marking breaking changes.

Note that in `beta` semantic-release does not point out BREAKING_CHANGES in the CHANGELOG.md file. Once we get to 1.0.0, that will also be improved.

**Comment by floryst** [comment]
Oh huh, so it doesn't. There are breaking change commits that don't show up in the beta release notes. Didn't realize that extended to the release notes generation as well.

**Comment by jadh4v** [comment]
Does `BREAKING CHANGE:` need to be in the commit title, or can be anywhere in the commit msg body?

**Review by jadh4v — APPROVED** [review]

**Comment by floryst** [comment]
> Does `BREAKING CHANGE:` need to be in the commit title, or can be anywhere in the commit msg body?

It needs to be in the message body.

**Pull request merged**
