### PR TITLE
fix(cli): Fix the cmakeargs for windows

### LINKED ISSUE #797: itk-wasm-cli doesn't work on windows with more than one cmake arg
Currently if on windows itk-wasm-cli incorrectly constructs a string for the cmake arguments passed to the build command after `"--"`. The cmakeargs variable is an Array of strings. It is added using the plus operator to another string, when adding an Array to a string the default behavior is to call Array.toString() which will join the strings with a comma. This results in cmake not recognizing the arguments correctly as it expects them to be delimited with a space. A potential fix is to call `cmakeArgs.join(' ')` instead.

### PR DESCRIPTION
**Pull request by alexDrinkwater**
fixes #797

### CODE REVIEW

**Comment by jspanchu** [comment]
FYI, @thewtex

**Review by thewtex — APPROVED** [review]
@alexDrinkwater @jspanchu thank you!!

**Comment by alexDrinkwater** [comment]
@thewtex Not sure of how you manage your releases, but when is this expected to be merged?

**Comment by thewtex** [comment]
@alexDrinkwater this took a little longer to be merged since CI needed to be approved for a first-time contributor on the repository.

Merging now, and this CD will deploy this to a new version after the CI builds complete.

**Pull request merged**
