### PR TITLE
feat(itk-dicom): Support loading multi-component dicom data with gdcm

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by sankhesh** [comment]
@thewtex Could you please review?

**Review by thewtex — CHANGES_REQUESTED** [review]
@sankhesh thanks!

Since RGB pixels are usually only supported with `unsigned char`, let's only use `RGBAPixel` and `RGBPixel` for `unsigned char`. For the others with `case 4` and `case 3`, let's use `itk::Vector` as with `case 2`.

**Comment by sankhesh** [comment]
Thanks @thewtex. I completely overlooked that `RGBPixels` typedefs to unsigned char only. While I fix it, is there a better way to do this without all the code duplication?

**Review by thewtex — APPROVED** [review]
:clap:

**Pull request merged**
